# Generated by Django 4.0.1 on 2022-01-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_feedback_alter_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['name'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.CharField(blank=True, max_length=150, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Имя'),
        ),
    ]
